spring:
    datasource:
        url: jdbc:mysql://localhost:3306/my_db?serverTimezone=UTC
        username: test
        password: 1111
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        show-sql: true
        generate-ddl: true
        properties:
            hibernate:
                format_sql: true