## 개발용
server:
    port: 8080
spring:
    output:
        ansi:
            enabled: always
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/my_db
        username: test
        password: 1111
