services:
  mysql80:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: my_db
      MYSQL_USER: test
      MYSQL_PASSWORD: 1111
    networks:
      - my-net1
    volumes:
      - ./backend/db/conf.d:/etc/mysql/conf.d
      - ./backend/db/data:/var/lib/mysql
      - ./backend/db/initdb.d:/docker-entrypoint-initdb.d
    env_file:
      ./backend/.env
    ports:
      - "3307:3306"
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    networks:
      - my-net1
    ports:                                          
      - "8080:8080"
    depends_on:
      - mysql80
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql80:3306/my_db?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=1111
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    networks:
      - my-net1
    ports:
      - "3000:3000"
    depends_on:
      - backend 
    environment:
      - BACKEND_URL=http://backend:8080
    restart: always

  nginx:
    image: nginx:latest
    networks:
      - my-net1
    restart: always
    volumes:
      - ./conf/domain.conf:/etc/nginx/conf.d/domain.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

networks:
  my-net1:
    driver: bridge