spring:
    profiles:
        active: dev
        include: secret
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                show-sql: true
                format_sql: true
                use_sql_comments: true
logging:
    level:
        org:
            springframework:
                security: DEBUG
    
